In [3]:
import sys
import os
sys.path.append(os.path.abspath("../"))

from src.preprocessing import load_data

df = load_data("../data/raw/smartphone_usage.csv")
df.head()

✅ Data loaded successfully

,transaction_id,user_id,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addicted_label
0,TXN00001,U00001,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes,NaN,0
1,TXN00002,U00002,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes,NaN,0
2,TXN00003,U00003,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,No,Mild,0
3,TXN00004,U00004,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,Yes,Moderate,1
4,TXN00005,U00005,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,No,Severe,1

In [4]:
print(df.shape)

(7500, 16)

In [5]:
print(df.columns)

Index(['transaction_id', 'user_id', 'age', 'gender', 'daily_screen_time_hours',
       'social_media_hours', 'gaming_hours', 'work_study_hours', 'sleep_hours',
       'notifications_per_day', 'app_opens_per_day', 'weekend_screen_time',
       'stress_level', 'academic_work_impact', 'addiction_level',
       'addicted_label'],
      dtype='object')

In [6]:
print(df.head())

  transaction_id user_id  age gender  daily_screen_time_hours  \
0       TXN00001  U00001   21   Male                     3.23
1       TXN00002  U00002   24  Other                     5.09
2       TXN00003  U00003   31  Other                     6.06
3       TXN00004  U00004   32  Other                     7.83
4       TXN00005  U00005   25   Male                     9.96

   social_media_hours  gaming_hours  work_study_hours  sleep_hours  \
0                2.01          0.89              4.55         7.55
1                3.81          2.24              4.44         7.66
2                1.36          3.83              2.35         4.92
3                5.85          1.51              3.54         8.23
4                5.92          3.42              5.27         6.21

   notifications_per_day  app_opens_per_day  weekend_screen_time stress_level  \
0                    248                154                 3.95       Medium
1                    127                 71                 6.71       Medium
2                     44                106                 8.68         High
3                    178                107                 9.77         High
4                    136                177                12.55          Low

  academic_work_impact addiction_level  addicted_label
0                  Yes             NaN               0
1                  Yes             NaN               0
2                   No            Mild               0
3                  Yes        Moderate               1
4                   No          Severe               1

In [7]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   transaction_id           7500 non-null   object
 1   user_id                  7500 non-null   object
 2   age                      7500 non-null   int64
 3   gender                   7500 non-null   object
 4   daily_screen_time_hours  7500 non-null   float64
 5   social_media_hours       7500 non-null   float64
 6   gaming_hours             7500 non-null   float64
 7   work_study_hours         7500 non-null   float64
 8   sleep_hours              7500 non-null   float64
 9   notifications_per_day    7500 non-null   int64
 10  app_opens_per_day        7500 non-null   int64
 11  weekend_screen_time      7500 non-null   float64
 12  stress_level             7500 non-null   object
 13  academic_work_impact     7500 non-null   object
 14  addiction_level          6681 non-null   object
 15  addicted_label           7500 non-null   int64
dtypes: float64(6), int64(4), object(6)
memory usage: 937.6+ KB
None

In [8]:
print(df.isnull().sum())

transaction_id               0
user_id                      0
age                          0
gender                       0
daily_screen_time_hours      0
social_media_hours           0
gaming_hours                 0
work_study_hours             0
sleep_hours                  0
notifications_per_day        0
app_opens_per_day            0
weekend_screen_time          0
stress_level                 0
academic_work_impact         0
addiction_level            819
addicted_label               0
dtype: int64

# Data Cleaning and Preprocessing

In [11]:
df = df.drop(columns=['transaction_id', 'user_id'])

In [12]:
df['addiction_level'].value_counts()

addiction_level
Moderate    2874
Severe      2434
Mild        1373
Name: count, dtype: int64

In [14]:
import pandas as pd

def fill_addiction_level(row):
    if pd.notnull(row['addiction_level']):
        return row['addiction_level']
    
    # Behavior-based logic
    if row['daily_screen_time_hours'] < 3:
        return 'Mild'
    elif row['daily_screen_time_hours'] < 6:
        return 'Moderate'
    else:
        return 'Severe'

df['addiction_level'] = df.apply(fill_addiction_level, axis=1)

In [16]:
df['addiction_level'].isnull().sum()

np.int64(0)

In [20]:
df.head()

,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addicted_label
0,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes,Moderate,0
1,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes,Moderate,0
2,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,No,Mild,0
3,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,Yes,Moderate,1
4,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,No,Severe,1

In [21]:
def fill_addiction_level(row):
    if pd.notnull(row['addiction_level']):
        return row['addiction_level']
    
    if row['addicted_label'] == 0:
        return 'Mild'
    else:
        if row['daily_screen_time_hours'] < 5:
            return 'Moderate'
        else:
            return 'Severe'

df['addiction_level'] = df.apply(fill_addiction_level, axis=1)

In [22]:
df.head()

,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addicted_label
0,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes,Moderate,0
1,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes,Moderate,0
2,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,No,Mild,0
3,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,Yes,Moderate,1
4,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,No,Severe,1